version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/openjdk:${OPENJDK_TAG}-${OPENJDK_VERSION}"
    container_name: "${APP_NAME}"
    command: /bin/bash -c "rmdir /var/www/app; ln -s /home/sindria/Projects/Sindria/giovannibrebbia/ing-sw-2020-balossini-barelli-brebbia/src /var/www/app; tail -f /dev/null"
    volumes:
      #- "${CODE_PATH}:${APP_CODE_PATH}"
      - "xdev-sindria_projects:/home/sindria/Projects"
    hostname: "${APP_NAME}.local"
    #ports:
    #  - "8080:80"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"

# =networks
networks:
  default:
    name: "vpc_${APP_NAME}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_tca-ingress:
#    external: true

# =volumes
volumes:
  xdev-sindria_projects:
    external: true
