package it.polimi.ingsw.common.event;

import java.util.List;
import java.util.Optional;

/**
 * An event may be generated by the View, the Model or the Controller
 * Events may be sent from the server or from a client
 * Events sent by clients have a sender, the player who sent the message
 * The model may send client-sent events to other clients, in which case the sender is the same as the original sender
 *
 * Events sent by the model may be sent to more than one player by specifying receivers
 */
public abstract class AbstractEvent {

    private List<String> receivers = null;

    public Optional<String> getSender() {
        return Optional.empty();
    }

    public Optional<List<String>> getReceivers() {
        return Optional.ofNullable(receivers);
    }

    public void setReceivers(List<String> receivers) {
        this.receivers = receivers;
    }

}
